package basic

const (
	RECODE_OK                  = 0
	RECODE_INTERNAL            = 500
	RECODE_UNKNOWN_ERR         = 999
	RECODE_CC_PUT_ERR          = 901
	RECODE_CC_GET_ERR          = 902
	RECODE_CC_DEL_ERR          = 903
	RECODE_JSON_ERR            = 904
	RECODE_AUTH_ERR            = 905
	RECODE_CC_INVOKE_ERR       = 906
	RECODE_GET_ID_ERR          = 907
	RECODE_TYPE_CONVERSION_ERR = 908
	RECODE_LIMITVISIT          = 909
	RECODE_REQ_PARAM_ERR       = 910
	RECODE_VERIFY_CODE_ERR     = 911

	RECODE_BALANCE_NOT_ENOUGH = 701
	RECODE_ZONEID_GET_ERR     = 722

	RECODE_TASK_STATUS_ERR            = 740
	RECODE_TASK_NOT_EXIST             = 742
	RECODE_TASK_CANNOT_TAKE           = 743
	RECODE_TASK_CANNOT_COMMIT         = 744
	RECODE_TASK_CANNOT_CONFIRM        = 745
	RECODE_TASK_CANNOT_BOUNS_TRANSFER = 746
	RECODE_TASK_CANNOT_CANCEL         = 748

	//用户
	RECODE_USER_ALREADY_EXISTS = 601
	RECODE_USER_NOT_EXISTS     = 602
	RECODE_USER_PASSWORD_ERROR = 603
)
